In [1]:
import pandas


In [2]:
d=pandas.read_csv("marks.csv")

In [3]:
y= d ['marks']

In [4]:
x=d['hrs']

In [5]:
x

0    4
1    5
2    6
3    7
4    8
Name: hrs, dtype: int64

In [6]:
x=x.values

In [7]:
x

array([4, 5, 6, 7, 8], dtype=int64)

In [8]:
x=x.reshape(-1,1)

In [9]:
from sklearn.linear_model import LinearRegression

In [10]:
mind=LinearRegression()

In [11]:
mind.fit(x,y)

LinearRegression()

In [12]:
mind.predict([[10]])

array([100.])

In [13]:
mind.coef_


array([10.])

In [14]:
import joblib

In [15]:
joblib.dump(mind, "marksmodelvb.pkl")

['marksmodelvb.pkl']